from coffea import hist
import numpy as np

cutflow_axis =  hist.Bin('cutFlow','cutFlow',20,0,20)
nMinus1_axis =  hist.Bin('Nminus1','i-th cut',20,0,20)
dataset_axis = hist.Cat("dataset", "Dataset")
region_axis  = hist.Cat("region", "region")

histograms ={
            "nCluster": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("nCluster", "nCluster", 4, 0, 4),
                cutflow_axis,
            ),                   
            "nCluster_dt": hist.Hist("Events",dataset_axis,region_axis,
                hist.Bin("nCluster", "nCluster", 4, 0, 4),
                cutflow_axis,
            ),                   
            "nCluster_n-1": hist.Hist("Events",dataset_axis,                
                hist.Bin("nCluster", "nCluster", 4, 0, 4),
                nMinus1_axis,
            ),                   
            "accept": hist.Hist("Events",dataset_axis,                
                hist.Bin("gLLP_csc", "gLLP_csc", 2, 0, 2),
                hist.Bin("gLLP_dt", "gLLP_dt", 2, 0, 2),
            ),
            ### CSC clusters                   
            "ClusterSize": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("ClusterSize", r"$N_{rechits}$", 50, 0, 2000),
            ),  
            "ClusterTime": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("ClusterTime", "ClusterTime", 40, -100, 100),
            ),
            "ClusterEta": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("ClusterEta", "ClusterEta", 40, -5, 5),
            ),
            "ClusterAvgStation10": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("ClusterAvgStation10", "ClusterAvgStation10", 20, 0, 5),
            ),
            "ClusterNStation10": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("ClusterNStation10", "ClusterNStation10", 5, 0, 5),
            ),
            "ClusterNStation10": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("ClusterNStation10", "ClusterNStation10", 5, 0, 5),
            ),
            "Cluster_match_gParticle_id": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("Cluster_match_gParticle_id", "Cluster_match_gParticle_id", 20000, -10000, 10000),
            ),
            "Cluster_match_gParticle_minDeltaR": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("Cluster_match_gParticle_minDeltaR", "Cluster_match_gParticle_minDeltaR", 40, 0, 5),
            ),
            "Cluster_match_gParticle_eta": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("Cluster_match_gParticle_eta", "Cluster_match_gParticle_eta", 40, -5, 5),
            ),
            "Cluster_match_gParticle_phi": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("Cluster_match_gParticle_phi", "Cluster_match_gParticle_phi", 40,-np.pi, np.pi),
            ),
            "Cluster_match_gParticle_e": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("Cluster_match_gParticle_e", "Cluster_match_gParticle_e", 50, 0, 500),
            ),
            "Cluster_match_gParticle_pt": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("Cluster_match_gParticle_pt", "Cluster_match_gParticle_pt", 50, 0, 500),
            ),
            "Cluster_match_gParticle_id_dt": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("Cluster_match_gParticle_id", "Cluster_match_gParticle_id", 20000, -10000, 10000),
            ),
            "Cluster_match_gParticle_minDeltaR_dt": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("Cluster_match_gParticle_minDeltaR", "Cluster_match_gParticle_minDeltaR", 40, 0, 5),
            ),
            "Cluster_match_gParticle_eta_dt": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("Cluster_match_gParticle_eta", "Cluster_match_gParticle_eta", 40, -5, 5),
            ),
            "Cluster_match_gParticle_phi_dt": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("Cluster_match_gParticle_phi", "Cluster_match_gParticle_phi", 40,-np.pi, np.pi),
            ),
            "Cluster_match_gParticle_e_dt": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("Cluster_match_gParticle_e", "Cluster_match_gParticle_e", 50, 0, 500),
            ),
            "Cluster_match_gParticle_pt_dt": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("Cluster_match_gParticle_pt", "Cluster_match_gParticle_pt", 50, 0, 500),
            ),
            "Cluster_match_gParticle_minDeltaR_cat": hist.Hist("Events",dataset_axis, region_axis,
                hist.Cat("pdgId", "pdgId"),
                hist.Bin("Cluster_match_gParticle_minDeltaR", "Cluster_match_gParticle_minDeltaR", 40, 0, 1),
            ),
            "Cluster_match_gParticle_eta_cat": hist.Hist("Events",dataset_axis, region_axis,
                hist.Cat("pdgId", "pdgId"),
                hist.Bin("Cluster_match_gParticle_eta", "Cluster_match_gParticle_eta", 80, -5, 5),
            ),
            "Cluster_match_gParticle_phi_cat": hist.Hist("Events",dataset_axis, region_axis,
                hist.Cat("pdgId", "pdgId"),
                hist.Bin("Cluster_match_gParticle_phi", "Cluster_match_gParticle_phi", 40,-np.pi, np.pi),
            ),
            "Cluster_match_gParticle_e_cat": hist.Hist("Events",dataset_axis, region_axis,
                hist.Cat("pdgId", "pdgId"),
                hist.Bin("Cluster_match_gParticle_e", "Cluster_match_gParticle_e", 70, 0, 200),
            ),
            "Cluster_match_gParticle_pt_cat": hist.Hist("Events",dataset_axis, region_axis,
                hist.Cat("pdgId", "pdgId"),
                hist.Bin("Cluster_match_gParticle_pt", "Cluster_match_gParticle_pt", 70, 0, 200),
            ),
            "Cluster_match_gParticle_minDeltaR_cat_dt": hist.Hist("Events",dataset_axis, region_axis,
                hist.Cat("pdgId", "pdgId"),
                hist.Bin("Cluster_match_gParticle_minDeltaR", "Cluster_match_gParticle_minDeltaR", 40, 0, 5),
            ),  
            "Cluster_match_gParticle_eta_cat_dt": hist.Hist("Events",dataset_axis, region_axis,
                hist.Cat("pdgId", "pdgId"),
                hist.Bin("Cluster_match_gParticle_eta", "Cluster_match_gParticle_eta", 40, -5, 5),
            ),
            "Cluster_match_gParticle_phi_cat_dt": hist.Hist("Events",dataset_axis, region_axis,
                hist.Cat("pdgId", "pdgId"),
                hist.Bin("Cluster_match_gParticle_phi", "Cluster_match_gParticle_phi", 40,-np.pi, np.pi),
            ),
            "Cluster_match_gParticle_e_cat_dt": hist.Hist("Events",dataset_axis, region_axis,
                hist.Cat("pdgId", "pdgId"),
                hist.Bin("Cluster_match_gParticle_e", "Cluster_match_gParticle_e", 50, 0, 500),
            ),
            "Cluster_match_gParticle_pt_cat_dt": hist.Hist("Events",dataset_axis, region_axis,
                hist.Cat("pdgId", "pdgId"),
                hist.Bin("Cluster_match_gParticle_pt", "Cluster_match_gParticle_pt", 50, 0, 500),
            ),
            "dphi_cluster_csc": hist.Hist("Events",dataset_axis,
                region_axis,                                          
                hist.Bin("ClusterSize", r"$N_{rechits}$", 100, 0, 1000),
                hist.Bin("dphi_lep", r'$\Delta\phi$(cluster,lep)', 30, 0, np.pi),
                hist.Bin("dphi_MET", r'$\Delta\phi$(cluster,MET)', 30, 0, np.pi),
            ),
            "ClusterID_csc": hist.Hist("Events",hist.Cat("dataset", "Dataset"),
                hist.Cat("region", "region"),
                hist.Bin("ClusterEta", r"Cluster $\eta$", 30, 0, 3),
                hist.Bin("ClusterAvgStation10", 'ClusterAvgStation10', 30, 0, 5),
                hist.Bin("ClusterNStation10", 'ClusterNStation10', 30, 0, 5),
            ),
            "ClusterSize_dt": hist.Hist("Events",dataset_axis,   
                region_axis,
                hist.Bin("ClusterSize", r"$N_{rechits}$", 50, 0, 2000),
            ),  
            "ClusterTime_dt": hist.Hist("Events",dataset_axis,                
                region_axis,
                hist.Bin("ClusterBx", "Cluster Bx", 20, -10, 10),
            ),   
            "ClusterEta_dt": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("ClusterEta", "ClusterEta", 40, -5, 5),
            ),
            "ClusterAvgStation10_dt": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("ClusterAvgStation10", "ClusterAvgStation10", 20, 0, 5),
            ),
            "ClusterNStation10_dt": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("ClusterNStation10", "ClusterNStation10", 5, 0, 5),
            ),

            "dphi_cluster_dt": hist.Hist("Events",dataset_axis,
                region_axis,                                          
                hist.Bin("ClusterSize", r"$N_{rechits}$", 100, 0, 1000),
                hist.Bin("dphi_lep", r'$\Delta\phi$(cluster,lep)', 30, 0, np.pi),
                hist.Bin("dphi_MET", r'$\Delta\phi$(cluster,MET)', 30, 0, np.pi),
            ),
            "ClusterID_dt": hist.Hist("Events",hist.Cat("dataset", "Dataset"),
                hist.Cat("region", "region"),
                hist.Bin("ClusterEta", r"Cluster $\eta$", 30, 0, 3),
                hist.Bin("ClusterAvgStation10", 'ClusterAvgStation10', 30, 0, 5),
                hist.Bin("ClusterNStation10", 'ClusterNStation10', 30, 0, 5),
            ),

            ## reco var.
            "nLeptons": hist.Hist("Events",dataset_axis,
                hist.Bin("nLeptons", "nLeptons", 5, 0, 5),
            ),            
            "elePt": hist.Hist("Events",dataset_axis,
                hist.Bin("elePt", "elePt", 40, 0, 100),
            ), 
            "eleEta": hist.Hist("Events",dataset_axis,
                hist.Bin("eleEta", "eleEta", 40, -5, 5),
            ),             
            "muPt": hist.Hist("Events",dataset_axis,
                hist.Bin("muPt", "muPt", 40, 0, 100),
            ), 
            "muEta": hist.Hist("Events",dataset_axis,
                hist.Bin("muEta", "muEta", 40, -5, 5),
            ),             

            "nJets": hist.Hist("Events",dataset_axis,
                hist.Bin("nJets", "nJets", 5, 0, 5),
            ),
            "jetPt": hist.Hist("Events",dataset_axis,
                region_axis,                                   
                hist.Bin("jetPt", "jetPt", 50, 50, 300),
            ),          
            "jetMet_dPhi": hist.Hist("Events",dataset_axis,
                hist.Bin("jetMet_dPhi", "jetMet_dPhi", 30, -np.pi, np.pi),
            ), 
            "metXYCorr": hist.Hist("Events",dataset_axis,
                region_axis,                                   
                hist.Bin("metXYCorr", "metXYCorr", 50, 0, 500),
            ),
            "MT": hist.Hist("Events",dataset_axis,                
                region_axis,                            
                hist.Bin("MT", "MT", 50, 0, 200),
            ),
            ## Event var            
            "nPU": hist.Hist("Events",dataset_axis,                
                hist.Bin("nPU", "nPU", 100, 0, 100),
            ),            
            "nPU_noweight": hist.Hist("Events",dataset_axis,                
                hist.Bin("nPU", "nPU", 100, 0, 100),
            ),            
            "gWPt": hist.Hist("Events",dataset_axis,                
                hist.Bin("gWPt", "gWPt", 50,0,500),
            ),            
            "gWPt_noweight": hist.Hist("Events",dataset_axis,                
                hist.Bin("gWPt", "gWPt", 50,0,500),
            ),           
            ## gen var.
            "glepdPhi": hist.Hist("Events",dataset_axis,                
                hist.Bin("gLLP_lepdPhi", r'$\Delta\phi$(gLLP,g_lep)', 30, 0,np.pi),
            ),                    
            "gLepPt": hist.Hist("Events",dataset_axis,                
                hist.Bin("gLepPt", 'gLepPt', 50, 0,500),
            ),                    
            "gLLP_e": hist.Hist("Events",dataset_axis,                
                hist.Bin("gLLP_e", 'gLLP_e', 50, 0,500),
            ),   
            "gLLP_pt": hist.Hist("Events",dataset_axis,                
                hist.Bin("gLLP_pt", 'gLLP_pt', 50, 0,500),
            ),   
            "gLLP_eta": hist.Hist("Events",dataset_axis,                
                hist.Bin("gLLP_eta", 'gLLP_eta', 40, -5,5),
            ),   
}
