from coffea import hist
import numpy as np

nMinus1_axis =  hist.Bin('Nminus1','i-th cut',20,0,20)
dataset_axis = hist.Cat("dataset", "Dataset")
cutFlow_axis = hist.Cat("cutflow", "cutflow")
region_axis  = hist.Cat("region", "region")
wpt_axis = hist.Bin("gWPt","W Pt[GeV]",
            np.array([   0.,    5.,   10.,   15.,   20.,   25.,   30.,   35.,   40.,
                        45.,   50.,   60.,   70.,   80.,   90.,  100.,  125.,  150.,
                        200.,  300.,  800., 1500.]))
histograms ={
            "cutflow": hist.Hist("Events",dataset_axis, region_axis, cutFlow_axis),
            "nCluster": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("nCluster", "nCluster", 4, 0, 4)
            ),                   
            "nCluster_dt": hist.Hist("Events",dataset_axis,region_axis,
                hist.Bin("nCluster", "nCluster", 4, 0, 4)
            ),                   
            "nCluster_n-1": hist.Hist("Events",dataset_axis,                
                hist.Bin("nCluster", "nCluster", 4, 0, 4)
            ),                   
            "accept": hist.Hist("Events",dataset_axis,                
                hist.Bin("gLLP_csc", "gLLP_csc", 2, 0, 2),
                hist.Bin("gLLP_dt", "gLLP_dt", 2, 0, 2),
            ),
            ### CSC clusters                   
            "ClusterSize": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("ClusterSize", r"$N_{rechits}$", 50, 0, 2000),
            ),  
            "ClusterTime": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("ClusterTime", "ClusterTime", 40, -100, 100),
            ),
            "ClusterEta": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("ClusterEta", "ClusterEta", 40, -5, 5),
            ),
            "ClusterAvgStation10": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("ClusterAvgStation10", "ClusterAvgStation10", 20, 0, 5),
            ),
            "ClusterNStation10": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("ClusterNStation10", "ClusterNStation10", 5, 0, 5),
            ),
            "ClusterNStation10": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("ClusterNStation10", "ClusterNStation10", 5, 0, 5),
            ),

            "dphi_cluster_csc": hist.Hist("Events",dataset_axis,
                region_axis,                                          
                hist.Bin("ClusterSize", r"$N_{rechits}$", 100, 0, 1000),
                hist.Bin("dphi_lep", r'$\Delta\phi$(cluster,lep)', 30, 0, np.pi),
                hist.Bin("dphi_MET", r'$\Delta\phi$(cluster,MET)', 30, 0, np.pi),
            ), 
            "dr_lep_and_dphi_lep": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("dr_lep", "dr_lep", 50, 0, 5),
                hist.Bin("dphi_lep", r'$\Delta\phi$(cluster,lep)', 30, 0, np.pi),
            ),
            ### DT cluster
            "ClusterEta_dt": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("ClusterEta", "ClusterEta", 40, -5, 5),
            ),
            "ClusterAvgStation10_dt": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("ClusterAvgStation10", "ClusterAvgStation10", 20, 0, 5),
            ),
            "ClusterNStation10_dt": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("ClusterNStation10", "ClusterNStation10", 5, 0, 5),
            ),
            "dr_lep_and_dphi_lep_dt": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("dr_lep", "dr_lep", 50, 0, 5),
                hist.Bin("dphi_lep", r'$\Delta\phi$(cluster,lep)', 30, 0, np.pi),
            ),
            "dphi_cluster_dt": hist.Hist("Events",dataset_axis,
                region_axis,                                          
                hist.Bin("ClusterSize", r"$N_{rechits}$", 100, 0, 1000),
                hist.Bin("dphi_lep", r'$\Delta\phi$(cluster,lep)', 30, 0, np.pi),
                hist.Bin("dphi_MET", r'$\Delta\phi$(cluster,MET)', 30, 0, np.pi),
              
                ),
            "ClusterID_dt": hist.Hist("Events",hist.Cat("dataset", "Dataset"),
                hist.Cat("region", "region"),
               
                hist.Bin("ClusterEta", r"Cluster $\eta$", 30, 0, 3),
                hist.Bin("ClusterAvgStation10", 'ClusterAvgStation10', 30, 0, 5),
                hist.Bin("ClusterNStation10", 'ClusterNStation10', 30, 0, 5),
            ),
            "ClusterEta_dt_dphi_lep": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("ClusterSize", r"$N_{rechits}$", 100, 0, 1000),
                hist.Bin("ClusterEta", "ClusterEta", 100, -5, 5),
                hist.Bin("dphi_lep", r'$\Delta\phi$(cluster,lep)',30, 0, np.pi),
            ),
            "ClusterAvgStation10_dt_dphi_lep": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("ClusterSize", r"$N_{rechits}$", 100, 0, 1000),
                hist.Bin("ClusterAvgStation10", "ClusterAvgStation10", 20, 0, 5),
                hist.Bin("dphi_lep", r'$\Delta\phi$(cluster,lep)', 30, 0, np.pi),
            ),
            "ClusterNStation10_dt_dphi_lep": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("ClusterSize", r"$N_{rechits}$", 100, 0, 1000),
                hist.Bin("ClusterNStation10", "ClusterNStation10", 5, 0, 5),
                hist.Bin("dphi_lep", r'$\Delta\phi$(cluster,lep)', 30, 0, np.pi),
            ),
            "ClusternMB1": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("ClusternMB1", "ClusternMB1",  100, 0, 100),
            ),

            "Cluster_MuonVeto_Pt_dt": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("Cluster_MuonVeto_pt", "Cluster_MuonVeto_pt", 40, 0, 100),
            ),


            "Cluster_MuonVeto_Eta_dt": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("Cluster_MuonVeto_eta", "Cluster_MuonVeto_eta",  40, -5, 5),
            ),


            "Cluster_MuonVeto_Phi_dt": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("Cluster_MuonVeto_phi", "Cluster_MuonVeto_phi",  30, -np.pi, np.pi),
            ),
            "ClusterID_csc": hist.Hist("Events",hist.Cat("dataset", "Dataset"),
                hist.Cat("region", "region"),
                hist.Bin("ClusterEta", r"Cluster $\eta$", 30, 0, 3),
                hist.Bin("ClusterAvgStation10", 'ClusterAvgStation10', 30, 0, 5),
                hist.Bin("ClusterNStation10", 'ClusterNStation10', 30, 0, 5),
            ),
            "ClusterSize_dt": hist.Hist("Events",dataset_axis,   
                region_axis,
                hist.Bin("ClusterSize", r"$N_{rechits}$", 50, 0, 2000),
            ),  
            "ClusterTime_dt": hist.Hist("Events",dataset_axis,                
                region_axis,
                hist.Bin("ClusterBx", "Cluster Bx", 20, -10, 10),
            ),   
            "ClusterEta_dt": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("ClusterEta", "ClusterEta", 40, -5, 5),
            ),
            "ClusterAvgStation10_dt": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("ClusterAvgStation10", "ClusterAvgStation10", 20, 0, 5),
            ),
            "ClusterNStation10_dt": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("ClusterNStation10", "ClusterNStation10", 5, 0, 5),
            ),

            "dphi_cluster_dt": hist.Hist("Events",dataset_axis,
                region_axis,                                          
                hist.Bin("ClusterSize", r"$N_{rechits}$", 100, 0, 1000),
                hist.Bin("dphi_lep", r'$\Delta\phi$(cluster,lep)', 30, 0, np.pi),
                hist.Bin("dphi_MET", r'$\Delta\phi$(cluster,MET)', 30, 0, np.pi),
            ),
            "ClusterID_dt": hist.Hist("Events",hist.Cat("dataset", "Dataset"),
                hist.Cat("region", "region"),
                hist.Bin("ClusterEta", r"Cluster $\eta$", 30, 0, 3),
                hist.Bin("ClusterAvgStation10", 'ClusterAvgStation10', 30, 0, 5),
                hist.Bin("ClusterNStation10", 'ClusterNStation10', 30, 0, 5),
            ),
            "ClusterMaxStationRatio_dt": hist.Hist("Events",dataset_axis, region_axis,
                hist.Bin("ClusterMaxStationRatio", "ClusterMaxStationRatio", 40, 0, 1),
            ),


            ## reco var.
            "nLeptons": hist.Hist("Events",dataset_axis,
                hist.Bin("nLeptons", "nLeptons", 5, 0, 5),
            ),

            "DiMuonMass": hist.Hist("Events",dataset_axis,
                hist.Bin("mass", "mass", 100, 0, 1000),
            ),
            "elePt": hist.Hist("Events",dataset_axis,
                hist.Bin("elePt", "elePt", 40, 0, 100),
            ), 
            "eleEta": hist.Hist("Events",dataset_axis,
                hist.Bin("eleEta", "eleEta", 40, -5, 5),
            ),             
            "muPt": hist.Hist("Events",dataset_axis,
                hist.Bin("muPt", "muPt", 40, 0, 100),
            ), 
            "muEta": hist.Hist("Events",dataset_axis,
                hist.Bin("muEta", "muEta", 40, -5, 5),
            ),             

            "nJets": hist.Hist("Events",dataset_axis,
                hist.Bin("nJets", "nJets", 5, 0, 5),
            ),
            "jetPt": hist.Hist("Events",dataset_axis,
                region_axis,                                   
                hist.Bin("jetPt", "jetPt", 50, 50, 300),
            ),          
            "jetMet_dPhi": hist.Hist("Events",dataset_axis,
                hist.Bin("jetMet_dPhi", "jetMet_dPhi", 30, -np.pi, np.pi),
            ), 
            "metXYCorr": hist.Hist("Events",dataset_axis,
                region_axis,                                   
                hist.Bin("metXYCorr", r"$E_{T}^{miss}$ [GeV]", 50, 0, 500),
            ),
            "MT": hist.Hist("Events",dataset_axis,                
                region_axis,                            
                hist.Bin("MT", "MT", 50, 0, 200),
            ),
            ## Event var            
            "weight_histo": hist.Hist("weight",dataset_axis,                
                region_axis,                
                hist.Bin("weight_input", "weight_input", 10000, -1, 1000),
            ),
            
            "nPU": hist.Hist("Events",dataset_axis,                
                hist.Bin("nPU", "nPU", 100, 0, 100),
            ),            
            "nPU_noweight": hist.Hist("Events",dataset_axis,                
                hist.Bin("nPU", "nPU", 100, 0, 100),
            ),            
            "gWPt": hist.Hist("Events",dataset_axis, wpt_axis),
            "gWPt_noweight": hist.Hist("Events",dataset_axis, wpt_axis),           
            ## gen var.
            "glepdPhi": hist.Hist("Events",dataset_axis, region_axis, 
                hist.Bin("gLLP_lepdPhi", r'$\Delta\phi$(gLLP,g_lep)', 30, 0,np.pi),
            ),                    
            "gLepPt": hist.Hist("Events",dataset_axis,                
                hist.Bin("gLepPt", 'gLepPt', 50, 0,500),
            ),                    
            "gLLP_e": hist.Hist("Events",dataset_axis,region_axis, 
                hist.Bin("gLLP_e", 'LLP energy[GeV]', 50, 0,500),
            ),   
            "gLLP_pt": hist.Hist("Events",dataset_axis,region_axis,    
                hist.Bin("gLLP_pt", 'LLP pT[GeV]', 50, 0,500),
            ),   
            "gLLP_eta": hist.Hist("Events",dataset_axis,region_axis,     
                hist.Bin("gLLP_eta", 'gLLP_eta', 40, -5,5),
            ),   
            "llp_cls_z":hist.Hist("Events",hist.Cat("dataset", "Dataset"),                
                hist.Bin("llp_z", "LLP decay Z[cm]", 40, 570, 1050),                    
                hist.Bin("cluster_z", "cluster Z[cm]", 40, 570, 1050),                                                         
            ), 
            "llp_cls_eff_z":hist.Hist("Events",hist.Cat("dataset", "Dataset"),
                hist.Bin("selection",'pass/fail', 2,0,2),
                hist.Bin("z", "LLP decay Z[cm]", 40, 570, 1050),
            ),
            "llp_cls_eff_r":hist.Hist("Events",hist.Cat("dataset", "Dataset"),
                hist.Bin("selection",'pass/fail', 2,0,2),
                hist.Bin("r", "LLP decay R[cm]", 20, 100, 700),
            ),
            "llp_cls_eff_e":hist.Hist("Events",hist.Cat("dataset", "Dataset"),
                hist.Bin("selection",'pass/fail', 2,0,2),
                hist.Bin("e", "LLP E[GeV]", 20, 0, 250),
            ),
            "llp_cls_dt_eff_z":hist.Hist("Events",hist.Cat("dataset", "Dataset"),
                hist.Bin("selection",'pass/fail', 2,0,2),
                hist.Bin("z", "LLP decay Z[cm]", 35, 0, 700),
            ),
            "llp_cls_dt_eff_r":hist.Hist("Events",hist.Cat("dataset", "Dataset"),
                hist.Bin("selection",'pass/fail', 2,0,2),
                hist.Bin("r", "LLP decay R[cm]", 40, 300, 700),
            ),
            "llp_cls_dt_eff_e":hist.Hist("Events",hist.Cat("dataset", "Dataset"),
                hist.Bin("selection",'pass/fail', 2,0,2),
                hist.Bin("e", "LLP E[GeV]", 20, 0, 250),
            ),
}
